module:
    _target_: src.models.segmentation.CustomSemanticSegmentationTask
    model: unet
    backbone: resnet50
    weights: imagenet
    in_channels: 3
    num_classes: 16
    lr: 1E-4
    image_size: ${image_size}
    loss: ce
    tmax: 50
    ignore_index: null

datamodule:
    _target_: src.datasets.MARIDADataModule
    root: benchmark-datasets/marida
    bands: rgb
    image_size: ${image_size}
    batch_size: 16
    num_workers: 16

trainer:
    _target_: lightning.Trainer
    max_epochs: 250
    accelerator: gpu
    precision: 16-mixed
    devices: 1
    log_every_n_steps: 25

image_size: 256
experiment_name: marida_unet_resnet50_rgb